name: Labels

on:
  pull_request:
    types: [ edited, opened, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  no_ticket:
    name: "Label whether ticket linked from title"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: "Check title and manage labels"
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const title = context.payload.pull_request.title;
            const regex = /#[0-9]+[ ,:]?/gm;
            const label = "no ticket";
            const hasMatch = regex.test(title);
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr_number = context.payload.pull_request.number;
            if (hasMatch && labels.includes(label)) {
              github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number: pr_number,
                name: label
              });
            } else if (!hasMatch && !labels.includes(label)) {
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: pr_number,
                labels: [label]
              });
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
